In [7]:
import numpy as np
import igl
import meshplot as mp
import scipy as sp

In [2]:
vertices, faces = igl.read_triangle_mesh("data/bunny.off")
mp.plot(vertices, faces)

E:\Programs\Anaconoda\envs\py38\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

# Vertex Normals

## Standard Vertex Normals

In [17]:
normals = igl.per_vertex_normals(vertices, faces, igl.PER_VERTEX_NORMALS_WEIGHTING_TYPE_UNIFORM)
# print(igl.PER_VERTEX_NORMALS_WEIGHTING_TYPE_UNIFORM)
print(normals[:10])

0
[[-0.3244438   0.63479412  0.70126504]
 [ 0.69665946  0.04959323  0.71568576]
 [-0.31520596  0.88800006  0.33481502]
 [-0.32060982  0.56377388  0.76116251]
 [ 0.32801732  0.71566914  0.61662169]
 [ 0.46752195 -0.82488363  0.31778959]
 [ 0.98616611  0.11195933  0.1222355 ]
 [-0.01527532  0.99911017 -0.03931317]
 [-0.18490131  0.83290319  0.52161651]
 [-0.07445458  0.95117097  0.29955018]]


## Area-weighted normals

In [19]:
# M = igl.massmatrix(vertices, faces, igl.MASSMATRIX_TYPE_VORONOI)
# areas = sp.sparse.diags(1 / M.diagonal())
area_weighted_normals = igl.per_vertex_normals(vertices, faces, igl.PER_VERTEX_NORMALS_WEIGHTING_TYPE_AREA )
print(area_weighted_normals[:10])
print(type(area_weighted_normals))

[[-0.29687978  0.63027118  0.71737064]
 [ 0.70667502  0.01503088  0.70737861]
 [-0.30699487  0.89707826  0.31781245]
 [-0.3133118   0.55226669  0.77255241]
 [ 0.32879667  0.71679194  0.61490004]
 [ 0.46674245 -0.78643132  0.40457047]
 [ 0.98758883  0.11273692  0.10935577]
 [ 0.01378248  0.99760904 -0.06772188]
 [-0.18590899  0.82948052  0.52668769]
 [-0.08298597  0.95042872  0.2996641 ]]
<class 'numpy.ndarray'>


## Mean-curvature normals